name: CI

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-latest, windows-latest, windows-2016, macOS-latest]

    steps:
      - name: Take photo of github.com
        uses: "muhameddelic/puppeteer-screenshot-action@test/cross-platform"
        with:
          url: https://github.com
          width: 2560
          height: 1440
          
      - name: Upload artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: screenshot
          path: $GITHUB_WORKSPACE/screenshots
