name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
      - name: Take photo of github.com
        uses: "action"
        with:
          url: https://github.com
          width: 2560
          height: 1440
